'use strict';
const $=id=>document.getElementById(id);const KEY='stance-sleep-cycle-v1';let latest=null;let deferredInstall=null;
function read(){return{wake:$('wake').value,latency:$('latency').value}}
function persist(){if($('remember').checked){localStorage.setItem(KEY,JSON.stringify(read()));$('storage').textContent='일정을 이 기기에 저장했습니다.'}else{localStorage.removeItem(KEY);$('storage').textContent='일정을 저장하지 않습니다.'}}
function render(){try{latest=SleepCore.calculateBedtimes($('wake').value,$('latency').value);$('error').textContent='';$('empty').hidden=true;$('output').hidden=false;$('wakeLabel').textContent=latest.wakeTime;$('cards').replaceChildren(...latest.candidates.map(item=>{const card=document.createElement('div');card.className='sleep-card'+(item.recommended?' recommended':'');card.innerHTML=`<span class="cycle">${item.cycles}주기<br>${item.sleepMinutes/60}시간</span><span><b class="time">${item.time}</b><small class="day">${item.dayOffset<0?' 전날':' 당일'}</small></span>${item.recommended?'<span class="badge">추천</span>':'<span></span>'}`;return card}));$('summary').textContent=`잠드는 데 ${latest.latency}분 걸린다고 가정했습니다. 알람은 ${latest.wakeTime}에 맞추세요.`;persist()}catch(e){latest=null;$('output').hidden=true;$('empty').hidden=false;$('error').textContent=e.message}}
$('form').addEventListener('submit',e=>{e.preventDefault();render()});$('sample').addEventListener('click',()=>{$('wake').value='07:00';$('latency').value='15';render()});$('clear').addEventListener('click',()=>{$('wake').value='';$('latency').value='15';$('remember').checked=false;localStorage.removeItem(KEY);latest=null;$('output').hidden=true;$('empty').hidden=false;$('error').textContent='';$('storage').textContent='입력값을 비웠습니다.'});document.querySelectorAll('[data-wake]').forEach(button=>button.addEventListener('click',()=>{$('wake').value=button.dataset.wake;render()}));$('remember').addEventListener('change',persist);
$('copy').addEventListener('click',async()=>{if(!latest)return;const text=`기상 ${latest.wakeTime} · 취침 후보 ${latest.candidates.map(x=>x.time+'('+x.cycles+'주기)').join(', ')}`;try{await navigator.clipboard.writeText(text);$('copyStatus').textContent='결과를 복사했습니다.'}catch{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();$('copyStatus').textContent=ok?'결과를 복사했습니다.':'복사하지 못했습니다. 결과를 길게 눌러 복사해 주세요.'}});
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved){$('wake').value=saved.wake||'';$('latency').value=saved.latency??'15';$('remember').checked=true;render();$('storage').textContent='저장된 일정을 불러왔습니다.'}}catch{localStorage.removeItem(KEY);$('storage').textContent='저장값을 읽지 못해 초기화했습니다.'}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('install').hidden=false});$('install').addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('install').hidden=true});
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('offlineStatus').textContent='오프라인 준비 완료 · 인터넷 없이도 다시 계산할 수 있습니다.'}).catch(()=>{$('offlineStatus').textContent='오프라인 준비에 실패했습니다. 온라인 계산은 계속 사용할 수 있습니다.'})}else{$('offlineStatus').textContent='이 브라우저는 오프라인 설치를 지원하지 않습니다.'}
