'use strict';
const C=OfficeCore,$=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),KR=v=>Number(v||0).toLocaleString('ko-KR');
let state=null,vault=null,view='dashboard',busy=false,importDraft=null,month=C.today().slice(0,7),query='',sort='date',filters={partner:'',type:'',status:'',warehouse:'',group:'',lot:'',balance:''};
const names={dashboard:'업무 현황',masters:'기준정보',attendance:'월 근태',payroll:'급여대장',import:'품목 가져오기',vouchers:'매입·매출',inventory:'재고 수불',ledger:'원장·마감',settings:'장부 관리'};
const types={purchase:'매입',sale:'매출',purchase_return:'매입 반품',sale_return:'매출 반품'},statusName={draft:'작성중',confirmed:'확정',cancelled:'취소',review:'검토중'};
const input=(name,label,value='',type='text',extra='')=>`<label>${E(label)}<input name="${name}" type="${type}" value="${E(value)}" ${extra}></label>`,select=(name,label,options,val='')=>`<label>${E(label)}<select name="${name}">${options.map(([v,n])=>`<option value="${E(v)}" ${v===val?'selected':''}>${E(n)}</option>`).join('')}</select></label>`,check=(name,label,value=false)=>`<label class="check"><input type="checkbox" name="${name}" ${value?'checked':''}>${E(label)}</label>`;
const opts=kind=>state[kind].filter(x=>x.active).map(x=>[x.code,x.code+' · '+x.name]);
const box=(title,body)=>`<section class="card"><h2>${title}</h2>${body}</section>`,table=(heads,rows)=>`<div class="tablewrap"><table><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${heads.length}" class="empty">등록된 자료가 없습니다</td></tr>`}</tbody></table></div>`;
const form=(id,body,button='서버에 저장')=>`<form id="${id}" class="gridform">${body}<div class="actions"><button class="primary">${button}</button></div></form>`;
const filterRow=()=>`<div class="filters">${input('month','조회 월',month,'month')}${input('query','검색',query,'search')}${select('sort','정렬',[['date','최신일자'],['name','이름 / 코드'],['amount','금액 큰 순']],sort)}</div>`;
const matching=x=>{if(query&&!JSON.stringify(x).toLowerCase().includes(query.toLowerCase()))return false;if(x.lines){if(filters.partner&&x.partner!==filters.partner||filters.type&&x.type!==filters.type||filters.status&&x.status!==filters.status)return false;if(filters.balance==='unpaid'&&C.balance(x)===0||filters.balance==='paid'&&C.balance(x)!==0)return false;}if(x.product){if(filters.warehouse&&x.warehouse!==filters.warehouse||filters.lot&&!(x.lot||'').includes(filters.lot))return false;}if(x.unit&&filters.group&&x.group!==filters.group)return false;return true},download=(name,body,type='text/csv;charset=utf-8')=>{let u=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
function notify(m,error=false){$('#notice').textContent=m;$('#notice').className=error?'error':'success';}
async function commit(action,fn){if(busy)throw Error('저장 중입니다');busy=true;document.body.classList.add('saving');let next=structuredClone(state);try{fn(next);if(vault)await OfficeStore.save(vault,next);state=next;render();notify(vault?'서버 저장과 재조회 검증 완료':'체험 장부에 반영했습니다 (서버 저장 없음)');}finally{busy=false;document.body.classList.remove('saving');}}
function sorted(rows){return [...rows].sort((a,b)=>sort==='amount'?(b.total||b.net||0)-(a.total||a.net||0):sort==='name'?String(a.name||a.code||a.product||a.employee).localeCompare(String(b.name||b.code||b.product||b.employee)):String(b.date||b.at||b.month||'').localeCompare(String(a.date||a.at||a.month||'')));}
function render(){if(!state)return;$('#auth').hidden=true;$('#workspace').hidden=false;$('#nav').innerHTML=Object.entries(names).map(([k,n])=>`<button data-view="${k}" class="${view===k?'selected':''}">${n}</button>`).join('');$('#page-title').textContent=names[view];$('#vault-label').textContent=vault?'장부 '+vault.id+' · 서버 v'+vault.revision:'체험 장부 · 현재 탭에서만 유지';let html=filterRow();if(['vouchers','ledger'].includes(view))html+=`<div class="filters extra">${select('fpartner','거래처',[['','전체'],...opts('partners')],filters.partner)}${select('ftype','전표유형',[['','전체'],...Object.entries(types)],filters.type)}${select('fstatus','전표상태',[['','전체'],...Object.entries(statusName).filter(([k])=>['draft','confirmed','cancelled'].includes(k))],filters.status)}${select('fbalance','결제상태',[['','전체'],['unpaid','잔액 있음'],['paid','결제 완료']],filters.balance)}</div>`;if(view==='inventory')html+=`<div class="filters extra">${select('fwarehouse','창고',[['','전체'],...opts('warehouses')],filters.warehouse)}${input('flot','LOT 검색',filters.lot)}</div>`;
if(view==='dashboard'){let vs=state.vouchers.filter(v=>v.status==='confirmed'&&v.date.startsWith(month)),purchase=vs.filter(v=>v.type==='purchase').reduce((a,v)=>a+v.total,0),sale=vs.filter(v=>v.type==='sale').reduce((a,v)=>a+v.total,0);html+=`<div class="stats">${[['이번 달 매입',purchase],['이번 달 매출',sale],['미수금',vs.filter(v=>v.type==='sale').reduce((a,v)=>a+C.balance(v),0)],['미지급금',vs.filter(v=>v.type==='purchase').reduce((a,v)=>a+C.balance(v),0)]].map(([n,v])=>`<article><span>${n}</span><strong>${KR(v)}<small>원</small></strong></article>`).join('')}</div>`;html+=box('오늘의 확인',`<ul><li>작성중 전표 ${state.vouchers.filter(v=>v.status==='draft').length}건</li><li>미확정 근태 ${state.attendance.filter(a=>!a.confirmed&&a.date.startsWith(month)).length}건</li><li>검토중 급여 ${state.payroll.filter(p=>p.status!=='confirmed'&&p.month===month).length}건</li><li>품목 ${state.products.length}개 · 직원 ${state.employees.length}명</li></ul><p>기준정보 → 월 근태 / 품목 가져오기 → 급여 / 전표 → 재고·원장 순서로 시작하세요.</p><p class="muted">조회 월 기준 합계입니다. 반품은 원장에서 별도로 구분합니다.</p>`);}
if(view==='masters'){html+=box('직원 · 급여 기준',form('employee',input('code','사번','','text','required')+input('name','이름','','text','required')+input('base','월 기본급 (원)',0,'number','min="0" required')+input('weeklyHours','주휴 인정시간 / 주',0,'number','min="0" max="168" step="0.1"')+input('hourly','주휴 계산용 시간단가 (원)',0,'number','min="0"')+check('weeklyIncluded','기본급에 주휴수당 포함',true)+check('active','재직',true)));html+=table(['사번 / 이름','기본급','주휴 기준','상태','수정'],state.employees.filter(matching).map(e=>[E(e.code)+' / '+E(e.name),KR(e.base),e.weeklyIncluded?'기본급 포함':`${e.weeklyHours}h × ${KR(e.hourly)}원 × 인정주수`,e.active?'재직':'중지',`<button data-edit="employees" data-code="${E(e.code)}">불러오기</button>`]));
html+=box('거래처',form('partner',input('code','거래처코드','','text','required')+input('name','거래처명','','text','required')+input('businessNumber','사업자번호')+input('terms','결제조건')+select('type','구분',[['both','매입·매출'],['purchase','매입'],['sale','매출']])+check('active','사용',true)))+table(['코드','이름','사업자번호','상태','수정'],state.partners.filter(matching).map(p=>[E(p.code),E(p.name),E(p.businessNumber),p.active?'사용':'중지',`<button data-edit="partners" data-code="${E(p.code)}">불러오기</button>`]));
html+=box('창고',form('warehouse',input('code','창고코드','','text','required')+input('name','창고명','','text','required')+check('active','사용',true)))+table(['코드','이름','상태','수정'],state.warehouses.filter(matching).map(w=>[E(w.code),E(w.name),w.active?'사용':'중지',`<button data-edit="warehouses" data-code="${E(w.code)}">불러오기</button>`]));
html+=box('품목 · SCM 코드 그대로',form('product',input('code','품목코드','','text','required')+input('name','품명','','text','required')+input('unit','단위','EA','text','required')+input('spec','규격')+select('tax','과세구분',[['taxable','과세'],['zero','영세'],['exempt','면세']])+input('purchase','매입단가',0,'number','min="0"')+input('sale','매출단가',0,'number','min="0"')+input('group','품목그룹')+input('barcode','바코드')+check('lot','LOT 관리')+check('active','사용',true)))+table(['코드','품명','단위','세금','그룹','수정'],state.products.filter(matching).map(p=>[E(p.code),E(p.name),E(p.unit),E(p.tax),E(p.group),`<button data-edit="products" data-code="${E(p.code)}">불러오기</button>`]));}
if(view==='attendance'){let emps=state.employees.filter(e=>e.active),days=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();html+=box('종이카드를 월 표로 입력',`<p>직원을 선택하면 일자별로 입력할 수 있습니다. 야간근무는 날짜를 나누어 기록하세요.</p>${select('attendanceEmployee','직원',emps.map(e=>[e.code,e.name]),sessionStorage.getItem('office-attendance-employee')||emps[0]?.code)}<form id="attendance"><div class="tablewrap"><table><thead><tr><th>날짜</th><th>구분</th><th>출근</th><th>퇴근</th><th>추가근무 분</th></tr></thead><tbody>${Array.from({length:days},(_,i)=>{let d=month+'-'+String(i+1).padStart(2,'0'),employee=sessionStorage.getItem('office-attendance-employee')||emps[0]?.code,a=state.attendance.find(a=>a.employee===employee&&a.date===d);return `<tr data-date="${d}"><td>${d}</td><td><select name="type"><option value="">미입력</option>${[['work','근무'],['absent','결근'],['leave','휴가'],['holiday','휴일']].map(([v,n])=>`<option value="${v}" ${a?.type===v?'selected':''}>${n}</option>`).join('')}</select></td><td><input name="start" type="time" value="${E(a?.start)}"></td><td><input name="end" type="time" value="${E(a?.end)}"></td><td><input name="overtime" type="number" min="0" value="${a?.overtime||0}"></td></tr>`}).join('')}</tbody></table></div>${check('confirmed','입력한 날짜의 근태를 관리자 확인 후 확정')}<button class="primary">근태 저장</button></form><details><summary>종이카드 표 붙여넣기</summary><p>날짜[TAB]구분(work/absent/leave/holiday)[TAB]출근[TAB]퇴근[TAB]추가근무 분</p><textarea id="attendance-paste" rows="5" placeholder="2026-10-01&#9;work&#9;09:00&#9;18:00&#9;0"></textarea><button id="paste-attendance">표에 넣기</button></details>`);html+=`<button data-export="attendance">월 근태 CSV</button>`;}
if(view==='payroll'){html+=box('급여 계산 · 관리자 검토',`<p>월 모든 날짜의 근태(휴일 포함)를 확정해야 계산할 수 있습니다. 기본급 + 별도 주휴수당 + 확정한 추가근로 금액 − 공제액. 기본급에 주휴 포함이면 주휴를 추가하지 않습니다. 인정 주수는 관리자가 근태를 검토해 입력합니다.</p>`+form('payroll',select('employee','직원',opts('employees'))+input('weeks','주휴 인정 주수',0,'number','min="0" max="6" step="0.1"')+input('extra','추가근로 확정금액',0,'number','min="0"')+input('deductions','공제액',0,'number','min="0"'),'계산 미리보기 저장'));html+=table(['직원 / 월','기본급','주휴','추가근로','공제','실지급액','상태 / 처리'],sorted(state.payroll.filter(p=>p.month===month&&matching(p))).map(p=>[E(p.employee)+' / '+p.month,KR(p.base),KR(p.weekly),KR(p.overtime),KR(p.deductions),`<strong>${KR(p.net)}</strong>`,`${statusName[p.status]} <button data-payroll-confirm="${p.id}">${p.status==='confirmed'?'확정 해제':'최종 확정'}</button><details><summary>계산 근거</summary><pre>${E(JSON.stringify(p.basis,null,2))}</pre></details>`]));html+=`<button data-export="payroll">급여대장 CSV</button>`;}
if(view==='import'){html+=box('품목 마스터 가져오기',`<p>첫 번째 표시 시트의 첫 행을 열 이름으로 사용합니다. xlsx와 UTF-8 CSV를 지원합니다. 옛 xls는 xlsx로 저장해 주세요. 제품코드는 문자열로 보존합니다.</p><input id="excel-file" type="file" accept=".xlsx,.csv"><p class="muted">파일 10MB · 최대 10,000행. 수식은 값으로 붙여넣고, 숫자 코드가 이미 잃어버린 앞자리 0은 원본에서 복원하세요.</p>`);if(importDraft){html+=box('열 매핑 확인',form('import-map',Object.keys(C.mapping(importDraft.headers)).map(k=>select(k,({code:'품목코드 *',name:'품명 *',unit:'단위 *',tax:'과세구분 *',spec:'규격',purchase:'매입단가',sale:'매출단가',barcode:'바코드',group:'그룹',lot:'LOT 관리',opening:'기초재고',warehouse:'창고코드',lotnumber:'LOT 번호'})[k],[['-1','가져오지 않음'],...importDraft.headers.map((h,i)=>[String(i),h])],String(importDraft.map[k]))).join(''),'매핑 확인 · 행 검증'));if(importDraft.preview){let {good,errors}=importDraft.preview;html+=box('반영 전 미리보기',`<p>정상 ${good.length}행 · 오류 ${errors.length}행. 기존 품목코드와 중복된 행은 반영하지 않습니다.</p>`+table(['행','코드','품명','단위','과세','기초재고'],good.slice(0,20).map(p=>[p.row,E(p.code),E(p.name),E(p.unit),E(p.tax),p.opening]))+table(['오류 행','원인'],errors.slice(0,20).map(e=>[e.row,E(e.error)]))+`<button id="import-apply" class="primary" ${good.length?'':'disabled'}>정상 ${good.length}행 최종 반영</button> <button id="import-errors">오류 CSV</button>`);}}html+=table(['파일','반영일','정상','오류'],state.imports.map(i=>[E(i.name),E(i.at),i.success,i.errors]));}
if(view==='vouchers'){html+=box('상세 전표 작성',`<form id="voucher" class="gridform">${select('type','유형',Object.entries(types))}${input('date','거래일',C.today(),'date','required')}${select('partner','거래처',opts('partners'))}${select('warehouse','창고',opts('warehouses'))}${input('document','증빙번호')}${input('due','결제기한','','date')}${input('memo','메모')}<div class="wide"><div class="tablewrap"><table><thead><tr><th>품목코드</th><th>수량</th><th>단가</th><th>LOT</th><th></th></tr></thead><tbody id="voucher-lines">${lineHTML()}</tbody></table></div><button id="add-line" type="button">+ 품목 행</button><p id="voucher-total" class="muted">품목을 선택하면 공급가·세액·합계를 미리 봅니다.</p><label>증빙 첨부 (PDF/PNG/JPEG 각 1MB, 합계 3MB)<input name="attachments" type="file" multiple accept="application/pdf,image/png,image/jpeg"></label></div><div class="actions"><button class="primary">임시저장</button></div></form>`);html+=table(['전표 / 일자','유형 / 거래처','금액 / 잔액','상태','업무'],sorted(state.vouchers.filter(v=>v.date.startsWith(month)&&matching(v))).map(v=>[E(v.document||v.id.slice(0,8))+'<br>'+v.date,types[v.type]+' / '+E(v.partner),`${KR(v.total)}원<br>잔액 ${KR(C.balance(v))}원`,statusName[v.status],`<details><summary>품목 ${v.lines.length}행</summary>${table(['코드','수량','단가','공급가','VAT','합계','LOT'],v.lines.map(l=>[E(l.product),l.quantity,KR(l.price),KR(l.supply),KR(l.vat),KR(l.total),E(l.lot)]))}<p>${E(v.memo)}</p>${v.attachments.map((a,i)=>`<button data-attachment="${v.id}" data-index="${i}">${E(a.name)}</button>`).join(' ')}</details>${v.status==='draft'?`<button data-confirm="${v.id}">확정</button>`:v.status==='confirmed'?`<button data-cancel="${v.id}">취소</button> <button data-payment="${v.id}">결제 기록</button> <button data-payment-undo="${v.id}">결제 취소</button> <button data-return="${v.id}">반품 전표</button>`:''}`]));}
if(view==='inventory'){html+=box('기초재고 · 수량 조정',form('movement',select('product','품목',opts('products'))+select('warehouse','창고',opts('warehouses'))+select('type','종류',[['opening','기초재고'],['adjustment','조정']])+input('delta','수량 증감 (출고는 음수)',0,'number','step="0.001" required')+input('lot','LOT')+input('reason','사유','','text','required')));let rows=[];for(let p of state.products)for(let w of state.warehouses){if(filters.warehouse&&filters.warehouse!==w.code)continue;let q=C.stock(state,p.code,w.code,filters.lot||undefined);rows.push([E(p.code),E(p.name),E(w.name),`<strong class="${q<0?'error':''}">${q}</strong>`,E(p.unit)]);}html+=table(['코드','품명','창고','현재고','단위'],rows.filter(r=>!query||r.join(' ').toLowerCase().includes(query.toLowerCase())));html+=box('수불 · 전표 추적',table(['일시','품목','창고','LOT','증감','원천 / 사유'],sorted(state.movements.filter(matching)).map(m=>[E(m.at.slice(0,16)),E(m.product),E(m.warehouse),E(m.lot),m.delta,E(m.source?.slice(0,8)||m.type)+' / '+E(m.reason)])));html+=`<button data-export="inventory">현재고 CSV</button> <button data-export="movements">수불 CSV</button>`;}
if(view==='ledger'){let vs=sorted(state.vouchers.filter(v=>v.status==='confirmed'&&v.date.startsWith(month)&&matching(v)));html+=box('매입·매출·미수·미지급 원장',table(['일자','유형','거래처','증빙','금액','결제액','잔액','기한'],vs.map(v=>[v.date,types[v.type],E(v.partner),E(v.document),KR(v.total),KR(v.total-C.balance(v)),KR(C.balance(v)),E(v.due)])));html+=`<button data-export="ledger">원장 CSV</button> <button id="close-month">${state.closings.includes(month)?'월 마감 해제':'검토 완료 · 월 마감'}</button><p>${state.closings.includes(month)?'확정된 월: 근태·급여·전표 변경을 잠갔습니다.':'작성중: 원장을 검토한 후 마감하세요.'}</p>`;}
if(view==='settings'){html+=box('장부 안전과 백업',`<p>장부 ID: <strong>${vault?E(vault.id):'체험 모드'}</strong></p><p>암호는 서버로 보내지 않습니다. 암호를 잃으면 복구할 수 없으므로 ID·암호와 암호화 백업을 별도로 보관하세요.</p><p>장부는 한 번에 한 기기에서 수정하세요. 저장 전 버전을 비교하지만 서버가 원자적 잠금을 제공하지 않아 동시에 저장하면 충돌할 수 있습니다. 공유 장부 ID는 접근 권한 관리 수단이 아닙니다.</p><button id="backup">암호화 백업 받기</button><button id="export-json">평문 자료 내보내기</button><label>백업 복원 (.json)<input id="restore-json" type="file" accept=".json"></label><p class="muted">평문 내보내기 파일에는 개인정보가 포함됩니다. 외부 공유에 주의하세요.</p>`);html+=box('재고 설정',form('settings',check('negativeStock','음수 재고 허용 (전표마다 관리자 재확인)',state.settings.negativeStock)));html+=box('감사 이력',table(['일시','작업','근거'],[...state.audit].reverse().filter(matching).slice(0,200).map(a=>[E(a.at.slice(0,19)),E(a.action),`<details><summary>상세</summary><pre>${E(JSON.stringify(a.detail,null,2))}</pre></details>`])));}
$('#content').innerHTML=html;wire();}
function lineHTML(l={}){return `<tr class="voucher-line"><td><select name="product">${opts('products').map(([v,n])=>`<option value="${E(v)}" ${v===l.product?'selected':''}>${E(n)}</option>`).join('')}</select></td><td><input name="quantity" type="number" min="0.001" step="0.001" value="${l.quantity||1}" required></td><td><input name="price" type="number" min="0" value="${l.price||0}" required></td><td><input name="lot" value="${E(l.lot)}"></td><td><button type="button" data-remove-line>×</button></td></tr>`;}
async function caught(fn){try{await fn()}catch(e){notify(e.message,true)}}
function field(f,n){return f.elements.namedItem(n)?.value||''}function values(f){return Object.fromEntries(new FormData(f));}function flag(f,n){return !!f.elements.namedItem(n)?.checked}
function onForm(id,fn){let f=$('#'+id);if(f)f.onsubmit=e=>{e.preventDefault();caught(()=>fn(f));};}
function wire(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});let mf=$('.filters input[name=month]');mf.onchange=()=>{if(/^\d{4}-\d{2}$/.test(mf.value)){month=mf.value;render()}};$('.filters input[name=query]').onchange=e=>{query=e.target.value;render()};$('.filters select[name=sort]').onchange=e=>{sort=e.target.value;render()};document.querySelectorAll('.extra [name]').forEach(el=>el.onchange=()=>{filters[el.name.slice(1)]=el.value;render()});
for(let [fid,kind] of [['employee','employees'],['partner','partners'],['product','products'],['warehouse','warehouses']])onForm(fid,f=>commit('master',s=>{let r=values(f);r.active=flag(f,'active');if(kind==='employees')r.weeklyIncluded=flag(f,'weeklyIncluded');if(kind==='products')r.lot=flag(f,'lot');C.master(s,kind,r)}));
document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{let k=b.dataset.edit,r=state[k].find(x=>x.code===b.dataset.code),f=$('#'+({employees:'employee',partners:'partner',products:'product',warehouses:'warehouse'})[k]);for(let [n,v] of Object.entries(r)){let el=f.elements.namedItem(n);if(el){if(el.type==='checkbox')el.checked=v;else el.value=v}}f.scrollIntoView({behavior:'smooth'});});
let ae=$('select[name=attendanceEmployee]');if(ae)ae.onchange=()=>{sessionStorage.setItem('office-attendance-employee',ae.value);render()};
onForm('attendance',f=>{let rows=Array.from(f.querySelectorAll('tr[data-date]')).filter(r=>r.querySelector('[name=type]').value).map(r=>Object.fromEntries([['date',r.dataset.date],['employee',ae.value],...['type','start','end','overtime'].map(n=>[n,r.querySelector('[name='+n+']').value])]));if(!rows.length)throw Error('입력된 근태가 없습니다');return commit('attendance',s=>C.attendance(s,rows,flag(f,'confirmed')))});
if($('#paste-attendance'))$('#paste-attendance').onclick=()=>caught(()=>{for(let line of $('#attendance-paste').value.trim().split('\n')){let [d,t,st,en,ot]=line.split('\t'),r=$('tr[data-date="'+CSS.escape(d)+'"]');if(!r)throw Error('조회 월에 없는 날짜: '+d);for(let [n,v] of [['type',t],['start',st],['end',en],['overtime',ot||'0']])r.querySelector('[name='+n+']').value=v||'';}notify('표에 반영했습니다. 검토 후 저장하세요.');});
onForm('payroll',f=>commit('payroll',s=>C.payroll(s,field(f,'employee'),month,field(f,'extra'),field(f,'deductions'),field(f,'weeks'))));
document.querySelectorAll('[data-payroll-confirm]').forEach(b=>b.onclick=()=>caught(()=>commit('payroll-status',s=>{if(s.closings.includes(month))throw Error('마감된 월입니다');let p=s.payroll.find(p=>p.id===b.dataset.payrollConfirm);p.status=p.status==='confirmed'?'review':'confirmed';C.log(s,'급여 '+statusName[p.status],{id:p.id,net:p.net});})));
if($('#excel-file'))$('#excel-file').onchange=e=>caught(async()=>{let file=e.target.files[0];if(!file)return;let hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())),v=>v.toString(16).padStart(2,'0')).join('');if(state.imports.some(i=>i.hash===hash))throw Error('이미 반영한 파일입니다');let rows=await OfficeExcel.read(file);if(rows.length<2)throw Error('열 이름과 데이터 행이 필요합니다');importDraft={headers:rows[0].map(String),rows:rows.slice(1),map:C.mapping(rows[0]),name:file.name,hash};render();});
onForm('import-map',f=>{for(let k of Object.keys(importDraft.map))importDraft.map[k]=Number(field(f,k));let required=['code','name','unit','tax'];if(required.some(k=>importDraft.map[k]<0))throw Error('필수 열 4개를 매핑하세요');if(new Set(required.map(k=>importDraft.map[k])).size<4)throw Error('필수 항목은 서로 다른 열에 매핑하세요');importDraft.preview=C.importRows(state,importDraft.rows,importDraft.map);render();});
if($('#import-apply'))$('#import-apply').onclick=()=>caught(async()=>{let batch=importDraft;if(state.imports.some(i=>i.hash===batch.hash))throw Error('이미 반영한 파일입니다');await commit('import',s=>{let result=C.importRows(s,batch.rows,batch.map);for(let p of result.good){C.master(s,'products',p);if(p.opening)C.movement(s,{product:p.code,warehouse:p.warehouse,lot:p.lotnumber,delta:p.opening,type:'opening',reason:'엑셀 기초재고'});}s.imports.push({name:batch.name,hash:batch.hash,map:batch.map,success:result.good.length,errors:result.errors.length,errorRows:result.errors,at:new Date().toISOString()});C.log(s,'품목 가져오기',{name:batch.name,count:result.good.length});});importDraft=null;render();});if($('#import-errors'))$('#import-errors').onclick=()=>download('품목-오류.csv',C.csv([['행','오류'],...importDraft.preview.errors.map(e=>[e.row,e.error])]));
if($('#add-line'))$('#add-line').onclick=()=>$('#voucher-lines').insertAdjacentHTML('beforeend',lineHTML());
let vf=$('#voucher');if(vf){vf.onclick=e=>{if(e.target.hasAttribute('data-remove-line'))e.target.closest('tr').remove();};vf.oninput=()=>{try{let ls=Array.from(vf.querySelectorAll('.voucher-line')).map(r=>{let p=state.products.find(p=>p.code===r.querySelector('[name=product]').value);return C.amounts(p,r.querySelector('[name=quantity]').value,r.querySelector('[name=price]').value)});$('#voucher-total').textContent=`공급가 ${KR(ls.reduce((n,l)=>n+l.supply,0))}원 · VAT ${KR(ls.reduce((n,l)=>n+l.vat,0))}원 · 합계 ${KR(ls.reduce((n,l)=>n+l.total,0))}원`;}catch(e){$('#voucher-total').textContent=e.message}};}
onForm('voucher',async f=>{let attachments=[],files=Array.from(f.elements.namedItem('attachments').files);if(files.reduce((n,x)=>n+x.size,0)>3*1024*1024)throw Error('첨부 합계는 3MB 이하입니다');for(let file of files){if(file.size>1024*1024||!['application/pdf','image/png','image/jpeg'].includes(file.type))throw Error('첨부 형식 또는 용량 오류');let data=await new Promise((ok,no)=>{let r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});attachments.push({name:file.name,type:file.type,data});}let inp=values(f);delete inp.attachments;inp.attachments=attachments;inp.lines=Array.from(f.querySelectorAll('.voucher-line')).map(r=>Object.fromEntries(['product','quantity','price','lot'].map(n=>[n,r.querySelector('[name='+n+']').value])));await commit('voucher',s=>C.voucher(s,inp));});
document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>caught(()=>commit('confirm',s=>{let v=s.vouchers.find(v=>v.id===b.dataset.confirm),allow=s.settings.negativeStock&&confirm('음수 재고가 발생할 경우에도 이번 전표를 확정합니까?');C.confirm(s,v.id,allow)})));
document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>caught(()=>{let reason=prompt('취소 사유');if(reason===null)return;return commit('cancel',s=>C.cancel(s,b.dataset.cancel,reason,s.settings.negativeStock&&confirm('취소 후 음수 재고가 발생해도 허용합니까?')))}));
document.querySelectorAll('[data-payment]').forEach(b=>b.onclick=()=>caught(()=>{let amount=prompt('결제 금액 (원)');if(amount===null)return;let method=prompt('결제수단 (현금/계좌/카드/기타)','계좌');if(method===null)return;return commit('payment',s=>C.pay(s,b.dataset.payment,amount,method,C.today()))}));
document.querySelectorAll('[data-payment-undo]').forEach(b=>b.onclick=()=>caught(()=>{let reason=prompt('결제 취소 사유 (마지막 결제 1건을 되돌림)');if(!reason)return;return commit('payment-undo',s=>{let v=s.vouchers.find(v=>v.id===b.dataset.paymentUndo);if(s.closings.includes(v.date.slice(0,7)))throw Error('마감된 월입니다');if(!v.payments.length)throw Error('결제 기록이 없습니다');let payment=v.payments.pop();C.log(s,'결제 취소',{voucher:v.id,payment,reason});});}));
document.querySelectorAll('[data-return]').forEach(b=>b.onclick=()=>caught(()=>{let v=state.vouchers.find(v=>v.id===b.dataset.return);if(!['purchase','sale'].includes(v.type))throw Error('원 매입·매출 전표에서 반품을 생성하세요');if(!confirm('원 전표 전체 수량의 반품 초안을 생성합니다. 부분 반품은 새 전표에서 수량을 입력하세요.'))return;return commit('return',s=>{C.voucher(s,{type:v.type+'_return',date:C.today(),partner:v.partner,warehouse:v.warehouse,lines:structuredClone(v.lines),document:'',memo:'원 전표 '+v.id+'의 전체 반품',original:v.id});});}));
document.querySelectorAll('[data-attachment]').forEach(b=>b.onclick=()=>{let a=state.vouchers.find(v=>v.id===b.dataset.attachment).attachments[Number(b.dataset.index)],link=document.createElement('a');link.href=a.data;link.download=a.name;link.click();});
onForm('movement',f=>commit('movement',s=>C.movement(s,values(f))));onForm('settings',f=>commit('settings',s=>{s.settings.negativeStock=flag(f,'negativeStock');C.log(s,'재고 설정 변경',s.settings)}));
if($('#close-month'))$('#close-month').onclick=()=>caught(()=>{if(!confirm(month+' 마감 상태를 변경합니까?'))return;return commit('closing',s=>{if(s.closings.includes(month))s.closings=s.closings.filter(m=>m!==month);else{if(s.vouchers.some(v=>v.date.startsWith(month)&&v.status==='draft')||s.payroll.some(p=>p.month===month&&p.status!=='confirmed'))throw Error('작성중 전표 또는 검토중 급여가 남아 있습니다');s.closings.push(month);}C.log(s,'월 마감 변경',{month,closed:s.closings.includes(month)});});});
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportCSV(b.dataset.export));
if($('#backup'))$('#backup').onclick=()=>caught(async()=>{if(!vault)throw Error('체험 모드는 평문 내보내기를 사용하세요');let p=await OfficeStore.seal(state,vault.key,vault.salt,vault.revision);download('office-encrypted-backup.json',JSON.stringify({vaultId:vault.id,...p},null,2),'application/json');});if($('#export-json'))$('#export-json').onclick=()=>{if(confirm('직원·급여를 포함한 평문 파일을 다운로드합니다. 보관 위치를 확인하세요.'))download('office-data.json',JSON.stringify(state,null,2),'application/json');};
if($('#restore-json'))$('#restore-json').onchange=e=>caught(async()=>{let file=e.target.files[0];if(!file||file.size>10*1024*1024)throw Error('백업은 10MB 이하여야 합니다');let p=JSON.parse(await file.text()),next;if(p.type==='encrypted_office_vault'){let pass=prompt('백업 암호');if(pass===null)return;let key=await OfficeStore.key(pass,p.salt);next=await OfficeStore.decrypt(p,key);}else next=p;for(let k of ['employees','products','partners','warehouses','attendance','payroll','vouchers','movements','imports','closings','audit'])if(!Array.isArray(next[k]))throw Error('백업 구조 오류: '+k);if(next.version!==1||!next.settings)throw Error('지원하지 않는 백업');if(!confirm('현재 장부를 백업 내용으로 교체합니까?'))return;await commit('restore',s=>{Object.assign(s,next);C.log(s,'백업 복원',{file:file.name});});});}
function exportCSV(kind){let rows=[];if(kind==='attendance')rows=[['직원','날짜','구분','출근','퇴근','추가근무분','확정'],...state.attendance.filter(a=>a.date.startsWith(month)).map(a=>[a.employee,a.date,a.type,a.start,a.end,a.overtime,a.confirmed])];if(kind==='payroll')rows=[['직원','월','기본급','주휴','추가근로','공제','지급액','상태'],...state.payroll.filter(p=>p.month===month).map(p=>[p.employee,p.month,p.base,p.weekly,p.overtime,p.deductions,p.net,p.status])];if(kind==='inventory')rows=[['품목','창고','현재고'],...state.products.flatMap(p=>state.warehouses.map(w=>[p.code,w.code,C.stock(state,p.code,w.code)]))];if(kind==='movements')rows=[['일시','품목','창고','LOT','증감','원천','사유'],...state.movements.map(m=>[m.at,m.product,m.warehouse,m.lot,m.delta,m.source,m.reason])];if(kind==='ledger')rows=[['일자','유형','거래처','증빙','합계','잔액','기한'],...state.vouchers.filter(v=>v.date.startsWith(month)&&v.status==='confirmed').map(v=>[v.date,types[v.type],v.partner,v.document,v.total,C.balance(v),v.due])];download(kind+'-'+month+'.csv',C.csv(rows));}
$('#create').onsubmit=e=>{e.preventDefault();caught(async()=>{let pass=field(e.target,'password');if(pass!==field(e.target,'repeat'))throw Error('암호 확인이 다릅니다');$('#create button').disabled=true;try{vault=await OfficeStore.create(pass,C.blank());state=vault.state;e.target.reset();render();notify('새 장부 ID '+vault.id+'를 기록하세요. 암호 분실 시 복구할 수 없습니다.');}finally{$('#create button').disabled=false;}})};
$('#open').onsubmit=e=>{e.preventDefault();caught(async()=>{let f=e.target;$('#open button').disabled=true;try{vault=await OfficeStore.open(field(f,'vaultId'),field(f,'password'));state=vault.state;f.reset();render();notify('서버 장부를 복호화해 열었습니다.');}finally{$('#open button').disabled=false;}})};
$('#demo').onclick=()=>{vault=null;state=C.blank();render();notify('체험 모드: 입력 자료는 새로고침하면 사라집니다. 서버 저장은 새 장부에서 시작하세요.');};
$('#lock').onclick=()=>{if(busy)return;state=null;vault=null;importDraft=null;$('#workspace').hidden=true;$('#auth').hidden=false;$('#content').innerHTML='';$('#notice').textContent='장부를 잠갔습니다.';};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
