(function(root){
'use strict';
const id=()=>crypto.randomUUID(), today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'});
const fail=m=>{throw new Error(m)}, num=(v,label='숫자',min=0)=>{let n=Number(v);if(!Number.isFinite(n)||n<min)fail(label+' 값을 확인하세요');return n}, money=v=>Math.round(num(v));
const date=v=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)fail('날짜를 확인하세요');return v};
function blank(){return {version:1,employees:[],products:[],partners:[],warehouses:[{code:'MAIN',name:'기본 창고',active:true}],attendance:[],payroll:[],vouchers:[],movements:[],imports:[],closings:[],audit:[],settings:{negativeStock:false}}}
function log(s,action,detail){s.audit.push({id:id(),at:new Date().toISOString(),action,detail});}
function master(s,kind,row){let list=s[kind],old=list.find(x=>x.code===row.code);if(!row.code?.trim()||!row.name?.trim())fail('코드와 이름은 필수입니다');
if(kind==='employees'){if(!old&&list.length>=29)fail('30인 미만: 최대 29명입니다');row.base=money(row.base);row.weeklyHours=num(row.weeklyHours);row.hourly=money(row.hourly);if(row.weeklyHours>168)fail('주휴시간은 168시간 이하여야 합니다');}
if(kind==='partners'&&row.businessNumber){row.businessNumber=row.businessNumber.replaceAll('-','');if(!/^\d{10}$/.test(row.businessNumber))fail('사업자번호는 숫자 10자리입니다');if(list.some(p=>p.code!==row.code&&p.businessNumber===row.businessNumber))fail('이미 등록된 사업자번호입니다');}if(kind==='products'){if(!row.unit?.trim())fail('단위는 필수입니다');if(!['taxable','zero','exempt'].includes(row.tax))fail('과세구분을 확인하세요');row.purchase=money(row.purchase);row.sale=money(row.sale);}
if(old)Object.assign(old,row);else list.push(row);log(s,'마스터 '+(old?'수정':'등록'),{kind,code:row.code});return row;}
function stock(s,product,warehouse,lot){return s.movements.filter(m=>m.product===product&&m.warehouse===warehouse&&(lot===undefined||m.lot===lot)).reduce((a,m)=>a+m.delta,0)}
function movement(s,m){if(!s.products.some(p=>p.code===m.product&&p.active))fail('활성 품목을 선택하세요');if(!s.warehouses.some(w=>w.code===m.warehouse&&w.active))fail('활성 창고를 선택하세요');let p=s.products.find(p=>p.code===m.product);if(p.lot&&!m.lot?.trim())fail('LOT가 필수인 품목입니다');let delta=Number(m.delta);if(m.type==='opening'&&delta<0)fail('기초재고는 양수여야 합니다');if(stock(s,m.product,m.warehouse,m.lot||'')+delta<0&&!s.settings.negativeStock)fail('음수 재고 조정이 차단되었습니다');if(!Number.isFinite(delta)||!delta)fail('조정 수량은 0이 아닌 숫자여야 합니다');if(!m.reason?.trim())fail('조정 사유를 입력하세요');s.movements.push({...m,delta,id:id(),at:new Date().toISOString()});log(s,'재고 '+m.type,{product:m.product,delta,reason:m.reason});}
function amounts(p,quantity,price){let q=num(quantity,'수량',0.000001),pr=money(price),supply=Math.round(q*pr),vat=p.tax==='taxable'?Math.round(supply*.1):0;if(!Number.isSafeInteger(supply))fail('금액이 너무 큽니다');return {quantity:q,price:pr,supply,vat,total:supply+vat};}
function voucher(s,input){date(input.date);if(s.closings.includes(input.date.slice(0,7)))fail('마감된 월입니다');if(!['purchase','sale','purchase_return','sale_return'].includes(input.type))fail('전표유형 오류');if(!s.partners.some(p=>p.code===input.partner&&p.active))fail('활성 거래처를 선택하세요');if(!s.warehouses.some(p=>p.code===input.warehouse&&p.active))fail('활성 창고를 선택하세요');if(!input.lines.length)fail('품목을 하나 이상 입력하세요');let lines=input.lines.map(l=>{let p=s.products.find(p=>p.code===l.product&&p.active);if(!p)fail('품목코드 '+l.product+'가 없습니다');if(p.lot&&!l.lot?.trim())fail(p.name+' LOT를 입력하세요');return {...l,...amounts(p,l.quantity,l.price)}});let total=lines.reduce((a,l)=>a+l.total,0);if(input.document&&s.vouchers.some(v=>v.document===input.document&&v.partner===input.partner&&v.type===input.type&&v.status!=='cancelled'))fail('중복 증빙번호입니다');let v={...input,id:id(),lines,total,status:'draft',payments:[],attachments:input.attachments||[]};s.vouchers.push(v);log(s,'전표 임시저장',{id:v.id,total});return v;}
function confirm(s,vid,allowNegative=false){let v=s.vouchers.find(v=>v.id===vid);if(!v||v.status!=='draft')fail('작성중 전표만 확정할 수 있습니다');if(s.closings.includes(v.date.slice(0,7)))fail('마감된 월입니다');if(!s.partners.some(p=>p.code===v.partner&&p.active)||!s.warehouses.some(w=>w.code===v.warehouse&&w.active)||v.lines.some(l=>!s.products.some(p=>p.code===l.product&&p.active)))fail('사용중지된 기준정보가 있습니다');let sign=['purchase','sale_return'].includes(v.type)?1:-1;let deltas=new Map();for(let l of v.lines){let k=l.product+'\0'+(l.lot||'');deltas.set(k,(deltas.get(k)||0)+sign*l.quantity);}let shortage=[];for(let [k,d] of deltas){let [p,lot]=k.split('\0');if(stock(s,p,v.warehouse,lot)+d<0)shortage.push(p+' ('+(stock(s,p,v.warehouse,lot)+d)+')');}if(shortage.length&&(!s.settings.negativeStock||!allowNegative))fail('음수 재고: '+shortage.join(', ')+' · 재고 설정과 관리자 확인이 필요합니다');v.status='confirmed';v.confirmedAt=new Date().toISOString();for(let l of v.lines)s.movements.push({id:id(),source:v.id,product:l.product,warehouse:v.warehouse,lot:l.lot||'',delta:sign*l.quantity,type:v.type,at:v.confirmedAt,reason:'전표 확정'});log(s,'전표 확정',{id:v.id,negativeOverride:shortage.length>0});return v;}
function cancel(s,vid,reason,allowNegative=false){let v=s.vouchers.find(v=>v.id===vid);if(!v||v.status!=='confirmed')fail('확정 전표만 취소할 수 있습니다');if(!reason?.trim())fail('취소 사유는 필수입니다');if(s.closings.includes(v.date.slice(0,7)))fail('마감된 월입니다');if(v.payments.length)fail('결제된 전표는 결제 취소를 먼저 처리하세요');const rows=s.movements.filter(m=>m.source===vid);let deltas=new Map();for(let m of rows){let k=m.product+'\0'+m.lot;deltas.set(k,(deltas.get(k)||0)-m.delta);}for(let [k,d] of deltas){let [p,l]=k.split('\0');if(stock(s,p,v.warehouse,l)+d<0&&(!s.settings.negativeStock||!allowNegative))fail('취소하면 음수 재고가 됩니다. 재고 설정과 관리자 확인이 필요합니다');}v.status='cancelled';v.cancelReason=reason;for(let m of rows)s.movements.push({...m,id:id(),delta:-m.delta,type:'reversal',at:new Date().toISOString(),reason});log(s,'전표 취소',{id:vid,reason});}
function pay(s,vid,amount,method,dateValue){let v=s.vouchers.find(v=>v.id===vid);if(!v||v.status!=='confirmed')fail('확정 전표에만 결제를 기록할 수 있습니다');date(dateValue);if(s.closings.includes(v.date.slice(0,7)))fail('마감된 월입니다');let a=money(amount);if(!a||a>balance(v))fail('결제액은 잔액 이내의 양수여야 합니다');v.payments.push({id:id(),amount:a,method,date:dateValue});log(s,'결제 등록',{id:vid,amount:a});}
const balance=v=>v.total-v.payments.reduce((a,p)=>a+p.amount,0);
function attendance(s,rows,confirmed){let keys=new Set();for(let r of rows){date(r.date);if(!s.employees.some(e=>e.code===r.employee&&e.active))fail('직원을 확인하세요');if(keys.has(r.employee+'|'+r.date))fail('중복 근태입니다');keys.add(r.employee+'|'+r.date);if(!['work','absent','leave','holiday'].includes(r.type))fail('근태구분 오류');if((r.start&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(r.start))||(r.end&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(r.end)))fail('시간은 HH:MM 형식입니다');if(r.start&&r.end&&r.end<=r.start)fail('퇴근이 출근보다 늦어야 합니다 (야간근무는 별도 날짜로 분리)');num(r.overtime,'추가근무 분');if(s.payroll.some(p=>p.month===r.date.slice(0,7)&&p.status==='confirmed'&&p.employee===r.employee))fail('급여 확정 후 근태 수정은 급여 확정 해제 후 가능합니다');if(s.closings.includes(r.date.slice(0,7)))fail('마감된 월입니다');}
for(let r of rows){s.attendance=s.attendance.filter(a=>!(a.employee===r.employee&&a.date===r.date));s.attendance.push({...r,overtime:Number(r.overtime),confirmed});}log(s,'월 근태 '+(confirmed?'확정':'저장'),{rows:rows.length});}
function payroll(s,employee,month,extra=0,deductions=0,weeks=0){let e=s.employees.find(e=>e.code===employee&&e.active);if(!e)fail('활성 직원을 선택하세요');let old=s.payroll.find(p=>p.employee===employee&&p.month===month);if(old?.status==='confirmed')fail('이미 확정된 급여입니다');if(s.closings.includes(month))fail('마감된 월입니다');let a=s.attendance.filter(a=>a.employee===employee&&a.date.startsWith(month));let days=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();if(a.length!==days||a.some(a=>!a.confirmed))fail('월 모든 날짜의 근태(휴일 포함)를 입력하고 먼저 확정하세요');let n=num(weeks,'인정 주 수');if(n>6)fail('인정 주 수는 6 이하여야 합니다');let weekly=e.weeklyIncluded?0:Math.round(e.weeklyHours*e.hourly*n),base=e.base,overtime=money(extra),deduct=money(deductions),net=base+weekly+overtime-deduct;if(net<0)fail('공제액이 지급총액보다 큽니다');let p={id:old?.id||id(),employee,month,base,weekly,overtime,deductions:deduct,net,status:'review',basis:{weeklyIncluded:e.weeklyIncluded,weeklyHours:e.weeklyHours,hourly:e.hourly,weeks:n,attendanceCount:a.length,overtimeMinutes:a.reduce((n,r)=>n+r.overtime,0)}};s.payroll=s.payroll.filter(p=>!(p.employee===employee&&p.month===month));s.payroll.push(p);log(s,'급여 초안 계산',{id:p.id,basis:p.basis});return p;}
function csv(rows){return '\ufeff'+rows.map(r=>r.map(v=>{let t=String(v??'');if(/^[=+@-]/.test(t))t="'"+t;return '"'+t.replaceAll('"','""')+'"'}).join(',')).join('\r\n');}
const aliases={code:['품목코드','제품코드','상품코드','code','productcode','itemcode'],name:['품명','품목명','제품명','상품명','name','productname'],unit:['단위','unit'],tax:['과세구분','세금구분','tax','taxtype'],spec:['규격','spec','specification'],purchase:['매입단가','구매단가','purchaseprice'],sale:['매출단가','판매단가','saleprice'],barcode:['바코드','barcode'],group:['그룹','품목그룹','group'],lot:['lot관리','로트관리','lotmanaged'],opening:['기초재고','openingstock'],warehouse:['창고','warehouse'],lotnumber:['lot','lot번호','로트번호']};
function mapping(headers){let out={};for(let [k,as] of Object.entries(aliases))out[k]=headers.findIndex(h=>as.includes(String(h).replace(/[\s_-]/g,'').toLowerCase()));return out;}
function importRows(s,rows,map){let seen=new Set();let good=[],errors=[];rows.forEach((r,i)=>{try{let get=k=>map[k]>=0?String(r[map[k]]??'').trim():'';let code=get('code'),name=get('name'),unit=get('unit'),tax=get('tax');let t={'과세':'taxable','영세':'zero','면세':'exempt',taxable:'taxable',zero:'zero',exempt:'exempt'}[tax];if(!code||!name||!unit||!t)fail('코드·품명·단위·과세구분을 확인하세요');if(seen.has(code)||s.products.some(p=>p.code===code))fail('중복 품목코드: '+code);seen.add(code);let lot=/^(true|1|y|예|사용)$/i.test(get('lot'));let opening=num(get('opening')||0,'기초재고'),warehouse=get('warehouse')||'MAIN';if(opening&&!s.warehouses.some(w=>w.code===warehouse&&w.active))fail('기초재고 창고가 없습니다');if(opening&&lot&&!get('lotnumber'))fail('기초재고 LOT가 필요합니다');good.push({row:i+2,code,name,unit,tax:t,spec:get('spec'),purchase:money(get('purchase')||0),sale:money(get('sale')||0),barcode:get('barcode'),group:get('group'),lot,active:true,opening,warehouse,lotnumber:get('lotnumber')});}catch(e){errors.push({row:i+2,error:e.message});}});return {good,errors};}
root.OfficeCore={id,today,fail,num,money,date,blank,log,master,stock,movement,amounts,voucher,confirm,cancel,pay,balance,attendance,payroll,csv,mapping,importRows};
if(typeof module!=='undefined')module.exports=root.OfficeCore;
})(typeof window!=='undefined'?window:globalThis);
