'use strict';
window.OfficeExcel=(()=>{
const xml=s=>{let d=new DOMParser().parseFromString(s,'application/xml');if(d.querySelector('parsererror'))throw Error('엑셀 XML 오류');return d}, text=n=>Array.from(n.getElementsByTagName('t'),t=>t.textContent).join('');
async function read(file){if(file.size>10*1024*1024)throw Error('파일은 10MB 이하로 올려주세요');if(/\.csv$/i.test(file.name)){const str=await file.text(),rows=[];let row=[],cell='',q=false;for(let i=0;i<str.length;i++){let c=str[i];if(c==='"'){if(q&&str[i+1]==='"'){cell+='"';i++}else q=!q;}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\r'||c==='\n')&&!q){if(c==='\r'&&str[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x))rows.push(row);row=[];cell=''}else cell+=c;}if(q)throw Error('CSV 따옴표가 닫히지 않았습니다');row.push(cell);if(row.some(x=>x))rows.push(row);if(rows[0]?.[0])rows[0][0]=rows[0][0].replace(/^\uFEFF/,'');return rows;}
if(!/\.xlsx$/i.test(file.name))throw Error('xlsx 또는 UTF-8 CSV 파일을 사용하세요. xls는 xlsx로 저장하세요');let b=new Uint8Array(await file.arrayBuffer()),v=new DataView(b.buffer),end=-1;for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--)if(v.getUint32(i,true)===0x06054b50){end=i;break;}if(end<0)throw Error('올바른 xlsx ZIP 파일이 아닙니다');let count=v.getUint16(end+10,true),off=v.getUint32(end+16,true),entries={};if(count>3000)throw Error('엑셀 ZIP 항목이 너무 많습니다');for(let i=0;i<count;i++){if(v.getUint32(off,true)!==0x02014b50)throw Error('ZIP 목록 오류');let method=v.getUint16(off+10,true),size=v.getUint32(off+20,true),plain=v.getUint32(off+24,true),nl=v.getUint16(off+28,true),el=v.getUint16(off+30,true),cl=v.getUint16(off+32,true),loc=v.getUint32(off+42,true),name=new TextDecoder().decode(b.slice(off+46,off+46+nl));if(plain>20*1024*1024)throw Error('압축 해제 크기가 너무 큽니다');entries[name]={method,size,plain,loc};off+=46+nl+el+cl;}
async function unpack(name){let e=entries[name];if(!e)return '';let l=e.loc;if(v.getUint32(l,true)!==0x04034b50)throw Error('ZIP 항목 오류');let start=l+30+v.getUint16(l+26,true)+v.getUint16(l+28,true);let data=b.slice(start,start+e.size);if(e.method===8){let stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));let reader=stream.getReader(),chunks=[],total=0;while(true){let {value,done}=await reader.read();if(done)break;total+=value.length;if(total>20*1024*1024){reader.cancel();throw Error('압축 해제 크기 제한 초과');}chunks.push(value);}data=new Uint8Array(total);let p=0;for(let c of chunks){data.set(c,p);p+=c.length;}}else if(e.method!==0)throw Error('지원하지 않는 ZIP 압축 방식');return new TextDecoder().decode(data);}
let strings=await unpack('xl/sharedStrings.xml'),shared=strings?Array.from(xml(strings).getElementsByTagName('si'),text):[];
let styleText=await unpack('xl/styles.xml'),styles=[],formats={};if(styleText){let d=xml(styleText);for(let n of d.getElementsByTagName('numFmt'))formats[n.getAttribute('numFmtId')]=n.getAttribute('formatCode');let x=d.getElementsByTagName('cellXfs')[0];if(x)styles.push(...Array.from(x.children,n=>formats[n.getAttribute('numFmtId')]||''));}
let workbook=xml(await unpack('xl/workbook.xml')),sheet=Array.from(workbook.getElementsByTagName('sheet')).find(n=>n.getAttribute('state')!=='hidden');if(!sheet)throw Error('읽을 수 있는 시트가 없습니다');let rid=sheet.getAttribute('r:id'),rels=xml(await unpack('xl/_rels/workbook.xml.rels')),rel=Array.from(rels.getElementsByTagName('Relationship')).find(n=>n.getAttribute('Id')===rid);if(!rel||rel.getAttribute('TargetMode')==='External')throw Error('외부 시트는 지원하지 않습니다');let target=rel.getAttribute('Target'),name=target.startsWith('/')?target.slice(1):'xl/'+target;name=name.replace(/^xl\/\.\//,'');if(name.includes('..'))throw Error('시트 경로 오류');let d=xml(await unpack(name)),rows=[];for(let r of d.getElementsByTagName('row')){let row=[];for(let c of r.getElementsByTagName('c')){let ref=c.getAttribute('r'),col=ref?.match(/^[A-Z]+/)?.[0];if(!col)continue;let ix=Array.from(col).reduce((a,ch)=>a*26+ch.charCodeAt(0)-64,0)-1;if(ix>200)throw Error('열은 201개 이하로 제한합니다');if(c.getElementsByTagName('f').length)throw Error('수식 셀은 값으로 붙여넣은 후 가져오세요');let raw=c.getElementsByTagName('v')[0]?.textContent||'',t=c.getAttribute('t'),value=t==='s'?shared[Number(raw)]||'':t==='inlineStr'?text(c):raw,format=styles[Number(c.getAttribute('s')||0)];if(/^0+$/.test(format)&&/^\d+$/.test(value))value=value.padStart(format.length,'0');row[ix]=value;}if(row.some(x=>x))rows.push(row);if(rows.length>10001)throw Error('최대 10,000행을 지원합니다');}return rows;}
return {read};
})();
