'use strict';
const $=id=>document.getElementById(id),key='yame-date-gap-v1',fmt=value=>new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short',timeZone:'UTC'}).format(new Date(value+'T00:00:00Z'));
let last=null;
function persist(){try{if($('remember').checked)localStorage.setItem(key,JSON.stringify({start:$('start').value,end:$('end').value}));else localStorage.removeItem(key);$('storageStatus').textContent=$('remember').checked?'이 브라우저에 날짜를 저장했습니다.':'';}catch(e){$('storageStatus').textContent='날짜 저장을 사용할 수 없지만 계산은 가능합니다.';}}
function reset(){last=null;$('result').hidden=true;$('empty').hidden=false;$('error').textContent='';}
function calculate(){reset();try{const r=calculateDateGap($('start').value,$('end').value);last=r;$('empty').hidden=true;$('result').hidden=false;$('gap').textContent=r.nights.toLocaleString('ko-KR')+'일';$('range').textContent=fmt(r.start)+' → '+fmt(r.end);$('trip').textContent=r.sameDay?'당일':r.nights.toLocaleString('ko-KR')+'박 '+r.calendarDays.toLocaleString('ko-KR')+'일';$('weeks').textContent=r.weeks?r.weeks+'주 '+r.extraDays+'일':r.nights+'일';$('meaning').textContent=r.sameDay?'시작일과 마지막 날이 같은 당일 일정입니다.':'두 날짜의 차이는 '+r.nights.toLocaleString('ko-KR')+'일이고, 양끝을 모두 세면 '+r.calendarDays.toLocaleString('ko-KR')+'일 일정입니다.';persist();}catch(e){$('error').textContent=e.message;}}
$('calculate').addEventListener('click',calculate);
for(const id of ['start','end'])$(id).addEventListener('change',()=>{reset();persist();});
$('remember').addEventListener('change',persist);
$('sample').addEventListener('click',()=>{$('start').value='2026-09-28';$('end').value='2026-10-03';calculate();});
$('clear').addEventListener('click',()=>{$('start').value='';$('end').value='';reset();$('empty').querySelector('strong').textContent='날짜를 비웠습니다';$('start').focus();persist();});
$('copy').addEventListener('click',async()=>{if(!last)return;const schedule=last.sameDay?'당일':last.nights+'박 '+last.calendarDays+'일';const period=last.weeks?last.weeks+'주 '+last.extraDays+'일':last.nights+'일';const text='날짜틈\n'+fmt(last.start)+' → '+fmt(last.end)+'\n차이 '+last.nights+'일 · '+schedule+' · '+period;try{await navigator.clipboard.writeText(text);$('meaning').textContent='계산 결과를 복사했습니다.';}catch(e){$('meaning').textContent='자동 복사가 차단됐어요. 결과를 직접 적어 주세요.';}});
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&typeof saved.start==='string'&&typeof saved.end==='string'){$('start').value=saved.start;$('end').value=saved.end;$('remember').checked=true;if(saved.start&&saved.end)calculate();}}catch(e){$('storageStatus').textContent='저장한 날짜를 읽지 못했습니다.';}
let prompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();prompt=e;$('install').hidden=false;});$('install').addEventListener('click',async()=>{if(!prompt)return;await prompt.prompt();prompt=null;$('install').hidden=true;});window.addEventListener('appinstalled',()=>{$('install').hidden=true;});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(()=>navigator.serviceWorker.ready).then(()=>{$('offline').textContent='오프라인 준비 완료 · 다음 방문에도 날짜를 계산할 수 있어요.';}).catch(()=>{$('offline').textContent='오프라인 준비에 실패했습니다. 연결 후 다시 방문해 주세요.';});else $('offline').textContent='이 브라우저는 오프라인 사용을 지원하지 않습니다.';
