(function(root){'use strict';
const base='https://localflow.ddns.net/uvb/v1/apps/small-business-groupware/items',enc=new TextEncoder(),dec=new TextDecoder(),b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))),un64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function request(url,method='GET',data){const r=await fetch(url,{method,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,cache:'no-store',signal:AbortSignal.timeout(20000)}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||('서버 응답 '+r.status));return j.data}
async function derive(password,salt){const m=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:un64(salt),iterations:310000,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function hashPassword(password,salt=b64(crypto.getRandomValues(new Uint8Array(16)))){if(password.length<8)throw Error('개인 비밀번호는 8자 이상입니다');const m=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:un64(salt),iterations:180000,hash:'SHA-256'},m,256);return {salt,hash:b64(bits),iterations:180000}}
async function verifyPassword(password,v){const got=await hashPassword(password,v.salt);if(got.hash.length!==v.hash.length)return false;let diff=0;for(let i=0;i<got.hash.length;i++)diff|=got.hash.charCodeAt(i)^v.hash.charCodeAt(i);return diff===0}
async function seal(state,key,salt,revision){const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode('small-groupware-v1|'+revision)},key,enc.encode(JSON.stringify(state)));return {type:'encrypted_small_groupware',version:1,revision,salt,iv:b64(iv),cipher:b64(cipher),updatedAt:new Date().toISOString()}}
async function decrypt(p,key){if(p.type!=='encrypted_small_groupware'||p.version!==1)throw Error('지원하지 않는 조직 공간입니다');try{return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(p.iv),additionalData:enc.encode('small-groupware-v1|'+p.revision)},key,un64(p.cipher))))}catch{throw Error('조직 암호가 다르거나 데이터가 손상되었습니다')}}
async function create(password,state){if(password.length<12)throw Error('조직 암호는 12자 이상입니다');const salt=b64(crypto.getRandomValues(new Uint8Array(16))),key=await derive(password,salt),payload=await seal(state,key,salt,0),item=await request(base,'POST',payload),check=await request(base+'/'+encodeURIComponent(item.id));if(check.data.cipher!==payload.cipher)throw Error('생성 후 저장 검증에 실패했습니다');return {id:item.id,key,salt,revision:0,state}}
async function open(id,password){if(!/^[A-Za-z0-9_-]{5,80}$/.test(id))throw Error('공간 ID를 확인하세요');const item=await request(base+'/'+encodeURIComponent(id)),key=await derive(password,item.data.salt),state=await decrypt(item.data,key);return {id,key,salt:item.data.salt,revision:item.data.revision,state}}
async function save(v,state){const url=base+'/'+encodeURIComponent(v.id),current=await request(url);if(current.data.revision!==v.revision)throw Error('다른 기기에서 변경했습니다. 새로 로그인해 다시 확인하세요');state.revision=(state.revision||0)+1;const payload=await seal(state,v.key,v.salt,v.revision+1);try{await request(url,'PATCH',payload)}catch(e){const check=await request(url);if(check.data.cipher!==payload.cipher)throw e}const check=await request(url);if(check.data.cipher!==payload.cipher)throw Error('저장 재조회 검증에 실패했습니다');v.revision=payload.revision;v.state=state;return v}
root.GroupwareAPI={hashPassword,verifyPassword,create,open,save,seal,decrypt};
})(this);
