(()=>{'use strict';
const C=GroupwareCore,A=GroupwareAPI,$=s=>document.querySelector(s);let vault,current,viewName='dashboard';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>v?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Seoul'}).format(new Date(v)):'없음';
function toast(m,b=false){const t=$('#toast');t.textContent=m;t.className=b?'show bad':'show';setTimeout(()=>t.className='',3200)}
function who(id){return C.member(vault.state,id)?.displayName||'알 수 없음'}function header(t,s,a=''){return '<div class="view-head"><div><p class="eyebrow">'+esc(s)+'</p><h1>'+esc(t)+'</h1></div>'+a+'</div>'}
async function mutate(fn,msg){const before=C.clone(vault.state);try{await fn(vault.state);C.generateDue(vault.state);await A.save(vault,vault.state);render();toast(msg)}catch(e){vault.state=before;toast(e.message,true);throw e}}
function enter(m){current=m;C.generateDue(vault.state);$('#gate').hidden=true;$('#workspace').hidden=false;$('#orgTitle').textContent=vault.state.organization.name;$('#currentUser').textContent=m.displayName+' · '+({owner:'소유자',admin:'관리자',member:'직원'}[m.role]);$('#sidebar [data-view="members"]').hidden=!C.canManage(m);render()}
$('#setupForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),out=$('#gateMessage');out.textContent='암호화 공간 생성 중…';try{const passwordVerifier=await A.hashPassword(f.get('password')),state=C.createState({orgName:f.get('orgName'),ownerName:f.get('ownerName'),loginId:f.get('loginId'),passwordVerifier});vault=await A.create(f.get('vaultPassword'),state);out.textContent='공간 ID: '+vault.id+' — 지금 별도로 기록하세요.';enter(state.members[0]);toast('공간 ID '+vault.id+'를 보관하세요')}catch(x){out.textContent=x.message}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),out=$('#gateMessage');out.textContent='조직 공간 여는 중…';try{vault=await A.open(f.get('spaceId').trim(),f.get('vaultPassword'));const m=C.findLogin(vault.state,f.get('loginId'));if(!m||m.status!=='active'||!(await A.verifyPassword(f.get('password'),m.passwordVerifier)))throw Error('로그인 정보가 다르거나 비활성 계정입니다');out.textContent='';enter(m)}catch(x){out.textContent=x.message}};
$('#logoutButton').onclick=()=>location.reload();$('#menuButton').onclick=()=>$('#sidebar').classList.toggle('open');$('#closeWork').onclick=$('#cancelWork').onclick=()=>$('#workDialog').close();
document.querySelectorAll('#sidebar button').forEach(b=>b.onclick=()=>{viewName=b.dataset.view;$('#sidebar').classList.remove('open');render()});
function render(){document.querySelectorAll('#sidebar button').forEach(b=>b.classList.toggle('active',b.dataset.view===viewName));({dashboard,board,members,ledger,audit,settings}[viewName]||dashboard)();$('#view').focus()}
const sortWorks=(a,b)=>(C.FINAL.includes(a.status)-C.FINAL.includes(b.status))||((a.dueAt?new Date(a.dueAt):Infinity)-(b.dueAt?new Date(b.dueAt):Infinity));
function cards(xs){return xs.length?'<div class="work-list">'+xs.map(w=>'<button class="work-card" data-id="'+w.id+'"><span class="pill '+w.priority+'">'+w.priority+'</span><b>'+esc(w.title)+'</b><small>'+w.status+' · '+esc(w.assigneeIds.map(who).join(', '))+' · '+fmt(w.dueAt)+'</small></button>').join('')+'</div>':'<p class="empty">표시할 업무가 없습니다.</p>'}
function bind(){document.querySelectorAll('.work-card').forEach(x=>x.onclick=()=>detail(x.dataset.id))}
function dashboard(){const d=C.dashboard(vault.state,current.id),mine=vault.state.works.filter(w=>w.assigneeIds.includes(current.id)&&C.ACTIVE.includes(w.status)).sort(sortWorks).slice(0,6),ns=vault.state.notifications.filter(n=>n.recipientIds.includes(current.id)).slice(-8).reverse();$('#view').innerHTML=header('오늘의 업무','개인 대시보드')+'<div class="stats"><article><b>'+d.mine+'</b><span>내 미완료</span></article><article><b>'+d.open+'</b><span>조직 미완료</span></article><article><b>'+d.overdue+'</b><span>기한 경과</span></article><article><b>'+d.notices+'</b><span>알림</span></article></div><section class="panel"><h2>내가 맡은 업무</h2>'+cards(mine)+'</section><section class="panel"><h2>알림</h2>'+(ns.length?'<ul class="notice-list">'+ns.map(n=>'<li><b>'+({assigned:'신규 배정',due_soon:'기한 임박',overdue:'기한 경과',reassign:'재배정 필요'}[n.kind]||n.kind)+'</b><span>'+n.workIds.map(id=>esc(vault.state.works.find(w=>w.id===id)?.title||id)).join(', ')+'</span></li>').join('')+'</ul>':'<p class="empty">새 알림이 없습니다.</p>')+'</section>';bind()}
function board(){const st=['대기','진행','보류','완료','취소'];$('#view').innerHTML=header('업무공유보드','상태·담당자·기한을 한눈에','<button id="newWork" class="primary">+ 업무 등록</button>')+'<div class="filters"><input id="q" placeholder="제목·본문·구성원 검색"><select id="af"><option value="">담당자 전체</option>'+vault.state.members.map(m=>'<option value="'+m.id+'">'+esc(m.displayName)+'</option>').join('')+'</select><select id="pf"><option value="">우선순위 전체</option><option>높음</option><option>보통</option><option>낮음</option></select></div><div class="board">'+st.map(s=>'<section><h2>'+s+' <span>'+vault.state.works.filter(w=>w.status===s).length+'</span></h2><div data-col="'+s+'"></div></section>').join('')+'</div>';$('#newWork').onclick=openNew;['q','af','pf'].forEach(id=>$('#'+id).oninput=filter);filter()}
function filter(){const q=($('#q')?.value||'').toLowerCase(),a=$('#af')?.value,p=$('#pf')?.value;document.querySelectorAll('[data-col]').forEach(col=>{const xs=vault.state.works.filter(w=>w.status===col.dataset.col&&(!q||(w.title+' '+w.description+' '+w.assigneeIds.map(who).join(' ')).toLowerCase().includes(q))&&(!a||w.assigneeIds.includes(a))&&(!p||w.priority===p)).sort(sortWorks);col.innerHTML=cards(xs)});bind()}
function openNew(){const f=$('#workForm'),s=f.elements.assignees;f.reset();s.innerHTML=vault.state.members.filter(m=>m.status==='active').map(m=>'<option value="'+m.id+'">'+esc(m.displayName)+'</option>').join('');$('#workDialog').showModal()}
$('#workForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await mutate(s=>C.createWork(s,current.id,{title:f.get('title'),description:f.get('description'),assigneeIds:f.getAll('assignees'),dueAt:f.get('dueAt')?new Date(f.get('dueAt')).toISOString():null,priority:f.get('priority')}),'업무를 등록했습니다');$('#workDialog').close()}catch{}};
function detail(id){const w=vault.state.works.find(x=>x.id===id),comments=vault.state.comments.filter(c=>c.workId===id),opts=(C.TRANSITIONS[w.status]||[]).map(x=>'<option>'+x+'</option>').join('');$('#detailBody').innerHTML='<header><div><p class="eyebrow">'+w.status+' · '+w.priority+'</p><h2>'+esc(w.title)+'</h2></div><button id="closeDetail" class="icon-button">✕</button></header><p>'+esc(w.description||'설명 없음')+'</p><dl><dt>담당자</dt><dd>'+esc(w.assigneeIds.map(who).join(', '))+'</dd><dt>작성자</dt><dd>'+esc(who(w.createdBy))+'</dd><dt>기한</dt><dd>'+fmt(w.dueAt)+'</dd><dt>사유/결과</dt><dd>'+esc(w.holdOrCancelReason||w.result||'없음')+'</dd></dl>'+(opts?'<form id="statusForm" class="inline-form"><select name="status">'+opts+'</select><input name="text" placeholder="보류·취소 사유 / 완료 결과"><button class="primary">상태 변경</button></form>':'')+'<h3>댓글</h3><ul class="comments">'+comments.map(c=>'<li><b>'+esc(who(c.authorId))+'</b><span>'+esc(c.body)+'</span><small>'+fmt(c.createdAt)+'</small></li>').join('')+'</ul><form id="commentForm" class="inline-form"><input name="body" placeholder="댓글 입력" required><button class="subtle">댓글 등록</button></form>';$('#detailDialog').showModal();$('#closeDetail').onclick=()=>$('#detailDialog').close();if($('#statusForm'))$('#statusForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),text=f.get('text');try{await mutate(s=>C.changeStatus(s,current.id,id,f.get('status'),{reason:text,result:text}),'상태 변경 완료');$('#detailDialog').close()}catch{}};$('#commentForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await mutate(s=>C.addComment(s,current.id,id,f.get('body')),'댓글 등록 완료');$('#detailDialog').close();detail(id)}catch{}}}
function members(){if(!C.canManage(current)){viewName='dashboard';return render()}$('#view').innerHTML=header('구성원 관리','활성 1~9명')+'<section class="panel"><form id="memberForm" class="member-form"><input name="displayName" placeholder="이름" required><input name="loginId" placeholder="로그인 ID" required><input name="password" type="password" minlength="8" placeholder="개인 비밀번호" required><select name="role"><option value="member">직원</option><option value="admin">관리자</option></select><button class="primary">추가</button></form></section><section class="panel table-wrap"><table><thead><tr><th>이름</th><th>로그인</th><th>역할</th><th>상태</th><th>관리</th></tr></thead><tbody>'+vault.state.members.map(m=>'<tr><td>'+esc(m.displayName)+'</td><td>'+esc(m.loginId)+'</td><td>'+m.role+'</td><td>'+m.status+'</td><td>'+(m.role==='owner'?'소유자 고정':'<button class="subtle toggle" data-id="'+m.id+'" data-next="'+(m.status==='active'?'inactive':'active')+'">'+(m.status==='active'?'비활성화':'활성화')+'</button>')+'</td></tr>').join('')+'</tbody></table></section>';$('#memberForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const passwordVerifier=await A.hashPassword(f.get('password'));await mutate(s=>C.addMember(s,current.id,{displayName:f.get('displayName'),loginId:f.get('loginId'),role:f.get('role'),passwordVerifier}),'계정 추가 완료')}catch(x){toast(x.message,true)}};document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>mutate(s=>C.setMemberStatus(s,current.id,b.dataset.id,b.dataset.next),'계정 상태 변경 완료').catch(()=>{}))}
function ledger(){$('#view').innerHTML=header('일손장부','기존 앱과 분리된 새 장부')+'<section class="ledger-callout"><div><h2>근태·급여부터 전표·재고까지</h2><p>이 그룹웨어 전용 저장공간 <code>small-business-groupware-ledger</code>를 사용합니다. 기존 일손장부 데이터는 가져오지 않습니다.</p><ul><li>월 근태·설정형 급여</li><li>품목 XLSX/CSV 가져오기</li><li>매입·매출·반품·재고 수불</li><li>결제·미수·미지급·감사 이력</li></ul></div><a class="primary" href="ledger/" target="_blank" rel="noopener">새 장부 열기 →</a></section><p class="warning">장부는 별도 암호화 금고입니다. 한 번에 한 기기에서 수정하세요.</p>'}
function audit(){const rows=vault.state.audit.slice().reverse();$('#view').innerHTML=header('통합 검색·기록','행위자·시각·상태 전이')+'<div class="filters"><input id="aq" placeholder="행위자·행위·대상 검색"><select id="at"><option value="">모듈 전체</option><option value="work">업무</option><option value="member">구성원</option><option value="organization">조직</option></select></div><section class="panel table-wrap"><table><thead><tr><th>한국 시각</th><th>행위자</th><th>행위</th><th>대상</th></tr></thead><tbody id="ar"></tbody></table></section>';function draw(){const q=$('#aq').value.toLowerCase(),t=$('#at').value;$('#ar').innerHTML=rows.filter(x=>(!t||x.targetType===t)&&(!q||(who(x.actorId)+' '+x.action+' '+x.targetId).toLowerCase().includes(q))).map(x=>'<tr><td>'+fmt(x.occurredAt)+'</td><td>'+esc(who(x.actorId))+'</td><td>'+esc(x.action)+'</td><td>'+esc(x.targetType)+' · '+esc(x.targetId)+'</td></tr>').join('')||'<tr><td colspan="4">기록 없음</td></tr>'}$('#aq').oninput=draw;$('#at').oninput=draw;draw()}
function settings(){$('#view').innerHTML=header('환경설정','조직·알림')+'<section class="panel"><form id="settingsForm"><label>조직명<input name="orgName" maxlength="100" value="'+esc(vault.state.organization.name)+'" '+(C.canManage(current)?'':'disabled')+'></label><label>기한 임박 기준<select name="hours" '+(C.canManage(current)?'':'disabled')+'><option value="12">12시간</option><option value="24">24시간</option><option value="48">48시간</option></select></label>'+(C.canManage(current)?'<button class="primary">저장</button>':'<p>변경은 소유자·관리자만 가능합니다.</p>')+'</form></section><section class="panel"><h2>저장·권한 한계</h2><p>UVB 자체에는 사용자 인증이나 원자적 잠금이 없습니다. 역할 권한은 복호화된 앱에서 적용되므로 공간 ID와 조직 암호는 신뢰할 구성원에게만 전달하세요.</p></section>';$('#settingsForm').elements.hours.value=String(vault.state.settings.dueAlertHours||24);$('#settingsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate(s=>{s.organization.name=f.get('orgName').trim();s.settings.dueAlertHours=Number(f.get('hours'));s.audit.push({id:'audit_'+Date.now(),actorId:current.id,action:'settings.update',targetType:'organization',targetId:s.organization.id,beforeAfter:{},occurredAt:new Date().toISOString()})},'설정 저장 완료').then(()=>$('#orgTitle').textContent=vault.state.organization.name).catch(()=>{})}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
})();
