(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.GroupwareCore=api})(this,function(){
'use strict';
const ACTIVE=['대기','진행','보류'],FINAL=['완료','취소'];
const TRANSITIONS={대기:['진행','보류','취소'],진행:['보류','완료','취소'],보류:['진행','취소'],완료:['진행'],취소:[]};
const clone=x=>JSON.parse(JSON.stringify(x)),uid=(p='id')=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9),now=()=>new Date().toISOString();
const login=v=>String(v||'').trim().toLowerCase();function ok(v,m){if(!v)throw Error(m)}
function audit(s,actor,action,type,id,before,after){s.audit.push({id:uid('audit'),actorId:actor,action,targetType:type,targetId:id,beforeAfter:{before,after},occurredAt:now()})}
function createState({orgName,ownerName,loginId,passwordVerifier}){ok(orgName.trim()&&ownerName.trim(),'조직명과 대표 이름이 필요합니다');const owner={id:uid('member'),displayName:ownerName.trim(),loginId:login(loginId),passwordVerifier,role:'owner',status:'active',createdAt:now()};ok(owner.loginId,'로그인 ID가 필요합니다');const s={schema:1,revision:0,organization:{id:uid('org'),name:orgName.trim(),memberLimit:9},members:[owner],works:[],comments:[],notifications:[],audit:[],settings:{dueAlertHours:24},ledger:{sourceSpecId:'3dRPbmFZqMs',copyMode:'separate_app',dataMigration:'new'},createdAt:now()};audit(s,owner.id,'organization.create','organization',s.organization.id,null,{name:s.organization.name});return s}
const member=(s,id)=>s.members.find(x=>x.id===id),canManage=m=>m.role==='owner'||m.role==='admin',findLogin=(s,id)=>s.members.find(x=>x.loginId===login(id));
function actor(s,id){const m=member(s,id);ok(m&&m.status==='active','활성 계정이 아닙니다');return m}
function addMember(s,actorId,input){const a=actor(s,actorId);ok(canManage(a),'구성원 관리 권한이 없습니다');ok(s.members.length<s.organization.memberLimit,'구성원은 최대 9명입니다');const id=login(input.loginId);ok(id&&!findLogin(s,id),'로그인 ID가 없거나 중복입니다');ok(String(input.displayName||'').trim(),'이름이 필요합니다');ok(['admin','member'].includes(input.role),'역할을 확인하세요');const m={id:uid('member'),displayName:input.displayName.trim(),loginId:id,passwordVerifier:input.passwordVerifier,role:input.role,status:'active',createdAt:now()};s.members.push(m);audit(s,actorId,'member.create','member',m.id,null,{displayName:m.displayName,loginId:m.loginId,role:m.role,status:m.status});return m}
function setMemberStatus(s,actorId,id,status){const a=actor(s,actorId),m=member(s,id);ok(canManage(a)&&m,'구성원 변경 권한이 없습니다');ok(['active','inactive'].includes(status),'상태를 확인하세요');ok(!(m.role==='owner'&&status==='inactive'),'소유자는 비활성화할 수 없습니다');const before={role:m.role,status:m.status};m.status=status;const reassign=s.works.filter(w=>ACTIVE.includes(w.status)&&w.assigneeIds.includes(id)).map(w=>w.id);audit(s,actorId,'member.status','member',id,before,{role:m.role,status,reassign});if(status==='inactive')s.notifications.push({id:uid('notice'),kind:'reassign',recipientIds:s.members.filter(x=>canManage(x)&&x.status==='active').map(x=>x.id),workIds:reassign,state:'pending',createdAt:now()});return reassign}
function setMemberRole(s,actorId,id,role){const a=actor(s,actorId),m=member(s,id);ok(a.role==='owner'&&m,'역할 변경은 소유자만 가능합니다');ok(['admin','member'].includes(role)&&m.role!=='owner','역할을 확인하세요');const before=m.role;m.role=role;audit(s,actorId,'member.role','member',id,{role:before},{role})}
function createWork(s,actorId,input){actor(s,actorId);const title=String(input.title||'').trim(),ids=[...new Set(input.assigneeIds||[])];ok(title&&title.length<=150,'제목은 1~150자입니다');ok(ids.length,'활성 담당자를 한 명 이상 선택하세요');ids.forEach(id=>ok(member(s,id)?.status==='active','활성 구성원만 담당자로 지정할 수 있습니다'));ok(['낮음','보통','높음'].includes(input.priority),'우선순위를 확인하세요');const w={id:uid('work'),title,description:String(input.description||'').trim(),assigneeIds:ids,dueAt:input.dueAt||null,priority:input.priority,status:'대기',holdOrCancelReason:'',result:'',createdBy:actorId,createdAt:now(),updatedAt:now()};s.works.push(w);audit(s,actorId,'work.create','work',w.id,null,clone(w));s.notifications.push({id:uid('notice'),kind:'assigned',recipientIds:ids,workIds:[w.id],state:'pending',createdAt:now()});return w}
function visibleWorks(s,actorId){actor(s,actorId);return s.works.slice()}
function changeStatus(s,actorId,id,next,{reason='',result=''}={}){const a=actor(s,actorId),w=s.works.find(x=>x.id===id);ok(w,'업무가 없습니다');ok(canManage(a)||w.createdBy===actorId||w.assigneeIds.includes(actorId),'상태 변경 권한이 없습니다');ok((TRANSITIONS[w.status]||[]).includes(next),'허용되지 않은 상태 전이입니다');if(next==='보류'||next==='취소')ok(reason.trim(),'보류·취소 사유가 필요합니다');if(next==='완료')ok(result.trim(),'완료 결과가 필요합니다');const before={status:w.status,reason:w.holdOrCancelReason,result:w.result};w.status=next;w.holdOrCancelReason=reason.trim();if(next==='완료')w.result=result.trim();w.updatedAt=now();audit(s,actorId,next==='진행'&&before.status==='완료'?'work.reopen':'work.status','work',id,before,{status:next,reason:w.holdOrCancelReason,result:w.result});return w}
function addComment(s,actorId,workId,body){actor(s,actorId);ok(s.works.some(x=>x.id===workId),'업무가 없습니다');body=String(body||'').trim();ok(body,'댓글을 입력하세요');const c={id:uid('comment'),workId,authorId:actorId,body,createdAt:now()};s.comments.push(c);audit(s,actorId,'comment.create','work',workId,null,{commentId:c.id});return c}
function generateDue(s,at=new Date()){const hours=s.settings.dueAlertHours||24,created=[];for(const w of s.works){if(!ACTIVE.includes(w.status)||!w.dueAt)continue;const diff=(new Date(w.dueAt)-at)/36e5;if(diff>hours)continue;const kind=diff<0?'overdue':'due_soon',key=kind+'|'+w.id+'|'+at.toISOString().slice(0,10);if(s.notifications.some(n=>n.key===key))continue;const n={id:uid('notice'),key,kind,recipientIds:[...new Set(w.assigneeIds.concat(s.members.filter(x=>canManage(x)&&x.status==='active').map(x=>x.id)))],workIds:[w.id],state:'pending',createdAt:now()};s.notifications.push(n);created.push(n)}return created}
function dashboard(s,actorId){const works=visibleWorks(s,actorId),mine=works.filter(w=>w.assigneeIds.includes(actorId)),open=works.filter(w=>ACTIVE.includes(w.status));return {open:open.length,mine:mine.filter(w=>ACTIVE.includes(w.status)).length,overdue:open.filter(w=>w.dueAt&&new Date(w.dueAt)<new Date()).length,notices:s.notifications.filter(n=>n.recipientIds.includes(actorId)&&n.state==='pending').length}}
return {ACTIVE,FINAL,TRANSITIONS,createState,findLogin,member,canManage,addMember,setMemberStatus,setMemberRole,createWork,visibleWorks,changeStatus,addComment,generateDue,dashboard,clone};
});
