'use strict';
const $=id=>document.getElementById(id);const fields=['size','sizeUnit','speed','speedUnit','efficiency'];const KEY='stance-transfer-time-v1';let latest=null;let deferredInstall=null;
function values(){return Object.fromEntries(fields.map(id=>[id,$(id).value]))}
function save(){if($('remember').checked){localStorage.setItem(KEY,JSON.stringify(values()));$('storage').textContent='조건을 이 기기에 저장했습니다.'}else{localStorage.removeItem(KEY);$('storage').textContent='전송 조건을 저장하지 않습니다.'}}
function render(){try{latest=TransferCore.calculateTransfer($('size').value,$('sizeUnit').value,$('speed').value,$('speedUnit').value,$('efficiency').value);$('error').textContent='';$('empty').hidden=true;$('output').hidden=false;$('duration').textContent=TransferCore.formatDuration(latest.seconds);$('fileLabel').textContent=`${latest.size} ${latest.sizeUnit}`;const effective=latest.effectiveBps/1e6;$('effective').textContent=(effective>=1000?(effective/1000).toFixed(2)+' Gbps':effective.toFixed(1)+' Mbps');const finish=new Date(Date.now()+latest.seconds*1000);$('finish').textContent=finish.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});$('summary').textContent=`${latest.speed} ${latest.speedUnit} 회선의 ${latest.efficiency}% 효율 기준입니다.`;$('bar').style.width=Math.max(8,Math.min(100,latest.efficiency))+'%';save()}catch(e){latest=null;$('output').hidden=true;$('empty').hidden=false;$('error').textContent=e.message}}
$('form').addEventListener('submit',e=>{e.preventDefault();render()});$('sample').addEventListener('click',()=>{$('size').value='10';$('sizeUnit').value='GB';$('speed').value='100';$('speedUnit').value='Mbps';$('efficiency').value='80';render()});$('clear').addEventListener('click',()=>{fields.forEach(id=>$(id).value=id==='efficiency'?'80':'');$('sizeUnit').value='GB';$('speedUnit').value='Mbps';$('remember').checked=false;localStorage.removeItem(KEY);latest=null;$('output').hidden=true;$('empty').hidden=false;$('error').textContent='';$('storage').textContent='입력값을 비웠습니다.'});document.querySelectorAll('[data-speed]').forEach(btn=>btn.addEventListener('click',()=>{$('speed').value=btn.dataset.speed;$('speedUnit').value=Number(btn.dataset.speed)>=1000?'Gbps':'Mbps';if($('speedUnit').value==='Gbps')$('speed').value=String(Number(btn.dataset.speed)/1000);if($('size').value)render()}));$('remember').addEventListener('change',()=>{save()});$('copy').addEventListener('click',async()=>{if(!latest)return;const text=`${latest.size} ${latest.sizeUnit} / ${latest.speed} ${latest.speedUnit} / 효율 ${latest.efficiency}% → ${TransferCore.formatDuration(latest.seconds)}`;try{await navigator.clipboard.writeText(text);$('copyStatus').textContent='결과를 복사했습니다.'}catch{$('copyStatus').textContent='복사하지 못했습니다. 결과를 길게 눌러 복사해 주세요.'}});
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved){fields.forEach(id=>{if(saved[id]!=null)$(id).value=saved[id]});$('remember').checked=true;$('storage').textContent='저장된 전송 조건을 불러왔습니다.';render()}}catch{localStorage.removeItem(KEY);$('storage').textContent='저장값을 읽지 못해 초기화했습니다.'}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('install').hidden=false});$('install').addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('install').hidden=true});
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('offlineStatus').textContent='오프라인 준비 완료 · 인터넷 없이도 다시 계산할 수 있습니다.'}).catch(()=>{$('offlineStatus').textContent='오프라인 준비에 실패했습니다. 온라인 계산은 계속 사용할 수 있습니다.'})}else{$('offlineStatus').textContent='이 브라우저는 오프라인 설치를 지원하지 않습니다.'}
