'use strict';
const $=id=>document.getElementById(id), storeKey='yame-fair-split-v1', money=n=>n.toLocaleString('ko-KR')+'원';
let last=null;
function persist(){try{if($('remember').checked)localStorage.setItem(storeKey,JSON.stringify({total:$('total').value,people:$('people').value,unit:$('unit').value}));else localStorage.removeItem(storeKey);$('storageStatus').textContent=$('remember').checked?'이 브라우저에 조건을 저장했습니다.':'';}catch(e){$('storageStatus').textContent='조건 저장을 사용할 수 없지만 계산은 가능합니다.';}}
function reset(){last=null;$('result').hidden=true;$('empty').hidden=false;$('error').textContent='';}
function calculate(){reset();try{const r=splitBill($('total').value,$('people').value,$('unit').value);last=r;$('empty').hidden=true;$('result').hidden=false;$('average').textContent=(r.total/r.people).toLocaleString('ko-KR',{maximumFractionDigits:2})+'원';$('baseAmount').textContent=money(r.base);$('basePeople').textContent=r.lowCount+'명';$('highAmount').textContent=money(r.high);$('highPeople').textContent=r.highCount+'명';$('highCard').classList.toggle('muted',r.highCount===0);$('looseBox').textContent=r.loose?('정산 단위로 나눌 수 없는 잔돈 '+money(r.loose)+'은 별도 처리해 주세요.'):'잔돈 없이 총액이 정확히 맞습니다.';const parts=[];if(r.highCount)parts.push(r.highCount+'명은 '+money(r.high));if(r.lowCount)parts.push(r.lowCount+'명은 '+money(r.base));$('summary').textContent=parts.join(', ')+'을 내면 됩니다.';persist();}catch(e){$('error').textContent=e.message;}}
$('calculate').addEventListener('click',calculate);
for(const id of ['total','people'])$(id).addEventListener('input',()=>{reset();persist();});
$('unit').addEventListener('change',()=>{reset();persist();});
$('remember').addEventListener('change',persist);
$('example').addEventListener('click',()=>{$('total').value='10000';$('people').value='3';$('unit').value='1';calculate();});
$('clear').addEventListener('click',()=>{$('total').value='';$('people').value='3';$('unit').value='1';reset();$('empty').querySelector('strong').textContent='조건을 기다리고 있어요';$('total').focus();persist();});
$('copy').addEventListener('click',async()=>{if(!last)return;let text='딱N빵 · '+money(last.total)+' ÷ '+last.people+'명\n';if(last.highCount)text+=last.highCount+'명: '+money(last.high)+'\n';if(last.lowCount)text+=last.lowCount+'명: '+money(last.base)+'\n';if(last.loose)text+='별도 잔돈: '+money(last.loose);try{await navigator.clipboard.writeText(text.trim());$('summary').textContent='정산 결과를 복사했습니다.';}catch(e){$('summary').textContent='자동 복사가 차단됐어요. 결과를 직접 적어 주세요.';}});
try{const saved=JSON.parse(localStorage.getItem(storeKey)||'null');if(saved){$('total').value=String(saved.total||'').slice(0,12);$('people').value=String(saved.people||'3').slice(0,3);if(['1','10','100','1000'].includes(String(saved.unit)))$('unit').value=String(saved.unit);$('remember').checked=true;if($('total').value)calculate();}}catch(e){$('storageStatus').textContent='저장된 조건을 읽지 못했습니다.';}
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').addEventListener('click',async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('install').hidden=true;});window.addEventListener('appinstalled',()=>{$('install').hidden=true;});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(()=>navigator.serviceWorker.ready).then(()=>{$('offline').textContent='오프라인 준비 완료 · 다음 방문에도 계산할 수 있어요.';}).catch(()=>{$('offline').textContent='오프라인 준비에 실패했습니다. 연결 후 다시 방문해 주세요.';});else $('offline').textContent='이 브라우저는 오프라인 사용을 지원하지 않습니다.';
