'use strict';
window.OfficeStore=(()=>{
const base='https://localflow.ddns.net/uvb/v1/apps/small-business-groupware-ledger/items', enc=new TextEncoder(),dec=new TextDecoder();
const b64=b=>btoa(Array.from(new Uint8Array(b),x=>String.fromCharCode(x)).join('')),un64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function api(url,method='GET',data){let r=await fetch(url,{method,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,cache:'no-store',signal:AbortSignal.timeout(20000)});let j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'서버 응답 '+r.status);return j.data;}
async function key(password,salt){return crypto.subtle.deriveKey({name:'PBKDF2',salt:un64(salt),iterations:310000,hash:'SHA-256'},await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function seal(state,k,salt,revision){let iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode('office-v1|'+revision)},k,enc.encode(JSON.stringify(state)));return {type:'encrypted_office_vault',version:1,revision,salt,iv:b64(iv),cipher:b64(cipher)};}
async function decrypt(p,k){if(p.type!=='encrypted_office_vault'||p.version!==1)throw Error('지원하지 않는 장부입니다');try{return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(p.iv),additionalData:enc.encode('office-v1|'+p.revision)},k,un64(p.cipher))))}catch{throw Error('암호가 다르거나 장부가 손상되었습니다');}}
async function create(password,state){if(password.length<12)throw Error('암호는 12자 이상으로 설정하세요');let salt=b64(crypto.getRandomValues(new Uint8Array(16))),k=await key(password,salt),payload=await seal(state,k,salt,0);let item;try{item=await api(base,'POST',payload)}catch(e){e.message+=' · 생성 응답이 불명확하면 다시 만들기 전에 서버 상태를 확인하세요';throw e}let check=await api(base+'/'+encodeURIComponent(item.id));if(check.data.cipher!==payload.cipher)throw Error('서버 저장 검증 실패');return {id:item.id,key:k,salt,revision:0,state};}
async function open(id,password){if(!/^[\w-]{5,64}$/.test(id))throw Error('장부 ID를 확인하세요');let i=await api(base+'/'+encodeURIComponent(id)),k=await key(password,i.data.salt),state=await decrypt(i.data,k);return {id,key:k,salt:i.data.salt,revision:i.data.revision,state};}
async function save(v,state){let u=base+'/'+encodeURIComponent(v.id),current=await api(u);if(current.data.revision!==v.revision)throw Error('다른 기기에서 변경되었습니다. 작업을 백업하고 새로 열어주세요');let p=await seal(state,v.key,v.salt,v.revision+1);try{await api(u,'PATCH',p)}catch(e){const check=await api(u);if(check.data.cipher!==p.cipher)throw e;}let check=await api(u);if(check.data.cipher!==p.cipher)throw Error('저장 검증 실패 또는 동시 수정 충돌');v.revision=p.revision;v.state=state;return v;}
return {create,open,save,seal,decrypt,key};
})();
