const assert=require('node:assert/strict');const C=require('../core.js');
const s=C.blank();C.master(s,'products',{code:'001',name:'품목',unit:'EA',tax:'taxable',purchase:100,sale:150,lot:false,active:true});C.master(s,'partners',{code:'P',name:'거래처',active:true});C.master(s,'employees',{code:'E',name:'직원',base:2000000,weeklyHours:8,hourly:10000,weeklyIncluded:false,active:true});
let buy=C.voucher(s,{type:'purchase',date:'2026-10-05',partner:'P',warehouse:'MAIN',document:'buy',lines:[{product:'001',quantity:10,price:100}]});assert.equal(buy.total,1100);C.confirm(s,buy.id);assert.equal(C.stock(s,'001','MAIN'),10);
let sale=C.voucher(s,{type:'sale',date:'2026-10-05',partner:'P',warehouse:'MAIN',lines:[{product:'001',quantity:3,price:150}]});assert.equal(sale.total,495);C.confirm(s,sale.id);assert.equal(C.stock(s,'001','MAIN'),7);C.pay(s,sale.id,200,'계좌','2026-10-05');assert.equal(C.balance(sale),295);assert.throws(()=>C.pay(s,sale.id,300,'계좌','2026-10-05'));assert.throws(()=>C.cancel(s,sale.id,'유효 취소 사유'));sale.payments=[];C.cancel(s,sale.id,'입력 오류');assert.equal(C.stock(s,'001','MAIN'),10);assert.throws(()=>C.cancel(s,sale.id,'재취소'));
let over=C.voucher(s,{type:'sale',date:'2026-10-05',partner:'P',warehouse:'MAIN',lines:[{product:'001',quantity:6,price:100},{product:'001',quantity:5,price:100}]});assert.throws(()=>C.confirm(s,over.id));assert.equal(over.status,'draft');
C.attendance(s,Array.from({length:31},(_,i)=>({employee:'E',date:'2026-10-'+String(i+1).padStart(2,'0'),type:'work',start:'09:00',end:'18:00',overtime:60})),true);let pay=C.payroll(s,'E','2026-10',10000,30000,4);assert.equal(pay.weekly,320000);assert.equal(pay.net,2300000);pay.status='confirmed';assert.throws(()=>C.attendance(s,[{employee:'E',date:'2026-10-01',type:'work',overtime:0}],true));
let imports=C.importRows(s,[['002','테스트','EA','과세'],['001','기존','EA','과세'],['003','잘못된','EA','미정']],{code:0,name:1,unit:2,tax:3});assert.equal(imports.good[0].code,'002');assert.equal(imports.errors.length,2);assert.ok(C.csv([['=CMD()']]).includes("'=CMD()"));
assert.throws(()=>C.voucher(s,{type:'purchase',date:'2026-02-30',partner:'P',warehouse:'MAIN',lines:[]}));
console.log('PASS: 전표 금액, 공급가/VAT, 중복 품목 합산 음수 차단, 수불/취소, 결제 한도, 급여 근거/확정 잠금, 엑셀 검증, CSV 수식 주입 차단');
